// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgfdkdobbznsislyajet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZmRrZG9iYnpuc2lzbHlhamV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzkxNjgsImV4cCI6MjA1ODcxNTE2OH0.RIWxha7lAM2Wgc-bUe67w0lFJBKxYOumimcZEJyZohY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);